function BuilderInitialState(options) {
   var defaultSettings = {
      title: [],
      tag: [],
      vendor: [],
      productType: [],
      availableForSale: true,
      productId: [],
      createdAt: [],
      updatedAt: [],
      connective: 'AND',
      limit: false,
      sortBy: 'title',
      reverse: false,
      pagination: true,
      paginationLoadMore: true,
      paginationHideInitial: false,
      pageSize: 9,
      limit: false,
      itemsPerRow: 3,
      excludes: [],
      dropzoneLoadMore: false,
      addToCartButtonColor: '#14273b',
      variantButtonColor: '',
      addToCartButtonText: 'Add to cart',
      hideQuantity: false,
      showQuantityLabel: true,
      minQuantity: 1,
      maxQuantity: false,
      showPriceRange: true,
      showCompareAt: false,
      quantityLabelText: 'Quantity',
      showFeaturedOnly: false,
      showZoom: false,
      noResultsText: 'No products left to show',
      infiniteScroll: false,
      infiniteScrollOffset: 100,
      titleColor: false,
      titleSize: false,
      myShopifyDomain: false,
      storefrontAccessToken: false
   }

   var defaultSettingsCopy = {
      title: [],
      tag: [],
      vendor: [],
      productType: [],
      availableForSale: true,
      productId: [],
      createdAt: [],
      updatedAt: [],
      connective: 'AND',
      limit: false,
      sortBy: 'title',
      reverse: false,
      pagination: true,
      paginationLoadMore: true,
      paginationHideInitial: false,
      pageSize: 9,
      limit: false,
      itemsPerRow: 3,
      excludes: [],
      dropzoneLoadMore: false,
      addToCartButtonColor: '#14273b',
      variantButtonColor: '',
      addToCartButtonText: 'Add to cart',
      hideQuantity: false,
      showQuantityLabel: true,
      minQuantity: 1,
      maxQuantity: false,
      showPriceRange: true,
      showCompareAt: false,
      quantityLabelText: 'Quantity',
      showFeaturedOnly: false,
      showZoom: false,
      noResultsText: 'No products left to show',
      infiniteScroll: false,
      infiniteScrollOffset: 100,
      titleColor: false,
      titleSize: false,
      myShopifyDomain: false,
      storefrontAccessToken: false
   }

   return {
      isReady: false,
      isShopReady: false,
      isLoading: false,
      hasCustomConnection: false,
      notices: [],
      defaultShortcode: '[wps_products]',
      defaultCreds: WP_Shopify.storefront,
      shortcode: '[wps_products]',
      defaultSettings: defaultSettingsCopy,
      payload: false,
      productOptions: [
         {
            componentConnectionParams: { first: 9, query: '*' },
            componentElement: document.getElementById('block-editor-inner'),
            componentId: false,
            componentOptions: defaultSettings,
            componentPayload: [],
            componentPayloadLastCursor: false,
            componentQueryParams: { first: 9, query: '*' },
            componentType: 'products'
         }
      ],
      settings: defaultSettings
   }
}

export { BuilderInitialState }
