function BuilderInitialState(options) {
   return {
      isReady: false,
      notices: [],
      shortcode: '[wps_products]',
      defaultSettings: WP_Shopify.settings,
      payload: false,
      productOptions: [
         {
            componentConnectionParams: { first: 9, query: '*' },
            componentElement: document.getElementById('block-editor-inner'),
            componentId: false,
            componentOptions: {
               title: '',
               tag: '',
               vendor: '',
               productType: '',
               availableForSale: 'any',
               productId: '',
               createdAt: '',
               updatedAt: '',
               connective: 'AND',
               limit: false,
               sortBy: 'title',
               reverse: false,
               pagination: true,
               pageSize: 9,
               limit: false,
               itemsPerRow: 3,
               excludes: [],
               dropzoneLoadMore: false,
               addToCartButtonColor: '#14273b',
               variantButtonColor: '',
               addToCartButtonText: 'Add to cart',
               hideQuantity: false,
               showQuantityLabel: true,
               minQuantity: 1,
               maxQuantity: false,
               showPriceRange: true,
               showCompareAt: false,
               quantityLabelText: 'Quantity',
               showFeaturedOnly: false,
               showZoom: false,
               noResultsText: 'No products found',
               infiniteScroll: false,
               infiniteScrollOffset: 100
            },
            componentPayload: [],
            componentPayloadLastCursor: false,
            componentQueryParams: { first: 9, query: '*' },
            componentType: 'products'
         }
      ],
      settings: {
         title: '',
         tag: '',
         vendor: '',
         productType: '',
         availableForSale: 'any',
         productId: '',
         createdAt: '',
         updatedAt: '',
         connective: 'AND',
         limit: false,
         sortBy: 'title',
         reverse: false,
         pagination: true,
         pageSize: 9,
         limit: false,
         itemsPerRow: 3,
         excludes: [],
         dropzoneLoadMore: false,
         addToCartButtonColor: '#14273b',
         variantButtonColor: '',
         addToCartButtonText: 'Add to cart',
         hideQuantity: false,
         showQuantityLabel: true,
         minQuantity: 1,
         maxQuantity: false,
         showPriceRange: true,
         showCompareAt: false,
         quantityLabelText: 'Quantity',
         showFeaturedOnly: false,
         showZoom: false,
         noResultsText: 'No products found',
         infiniteScroll: false,
         infiniteScrollOffset: 100
      }
   }
}

export { BuilderInitialState }
